language: node_js

node_js:
- 12
sudo: required

branches:
  only:
  - master

env:
  - TARGET=web-app
  - TARGET=auth-service
  - TARGET=posts-service

before_script:
  - chmod +x devops/scripts/ci-lint.sh
  - chmod +x devops/scripts/ci-test.sh
  - chmod +x devops/scripts/ci-build-image.sh

script:
- npm install
# lint step
- ./devops/scripts/ci-lint.sh $TARGET
# test step
- ./devops/scripts/ci-test.sh $TARGET
# build step
- ./devops/scripts/ci-build-image.sh $TARGET

# jobs:
#   include:
#     - stage: "Lint"
#       if: type = pull_request
#       name: $TARGET
#       script: ./devops/scripts/ci-lint.sh $TARGET

    # - stage: "Test"
    #   if: type = pull_request
    #   name: "web app"
    #   script: ./devops/scripts/ci-test.sh web-app
    # - script: ./devops/scripts/ci-test.sh auth-service
    #   name: "auth service"
    # - script: ./devops/scripts/ci-test.sh posts-service
    #   name: "posts service"

    # - stage: "Build and publish"
    #   if: type = push
    #   name: "web app"
    #   script: ./devops/scripts/ci-build-image.sh web-app pdp-web-app
    # - script: ./devops/scripts/ci-build-image.sh auth-service pdp-auth-svc
    #   name: "auth service"
    # - script: ./devops/scripts/ci-build-image.sh posts-service pdp-posts-svc
    #   name: "posts service"
