language: node_js

node_js:
- 12
sudo: required

branches:
  only:
  - master

env:
  - TARGET=web-app
  - TARGET=auth-service
  - TARGET=posts-service

before_script:
  - chmod +x devops/scripts/ci-lint.sh
  - chmod +x devops/scripts/ci-test.sh
  - chmod +x devops/scripts/ci-build-image.sh

script:
# install step
- ./devops/scripts/ci-install.sh
# lint step
- ./devops/scripts/ci-lint.sh
# test step
- ./devops/scripts/ci-test.sh
# build step
- ./devops/scripts/ci-build-image.sh

