language: node_js

node_js:
- 12

sudo: required

branches:
  only:
  - master

script:
- npm run ci:install
- npm run ci:lint
- npm run ci:test

env:
  global:
    secure: qllm4GlZ0QgO3Up24mLRSai/InWEpRcSuXTRZFcyOxh8WfAyRm8wn5igRqq0T36k8W2BwefwjlhwpQcA4VYnm15um7alo95j7WElVT/RCLpK/ZVsR+5z31gxyGk9ixCludMSZ3Ha0rTNng1TeBLMh8+xTHee5Lz6JdTC7k54rexcBbW7lMGEfsUftX4HYkS9vst6TVWoQ5hchQgkChFl3Lg/sgvj6weE7yIqbbkv6UAPs5xFds2YDyit50oByxQt2h8ch/ZFC7HhGyJu+EWlWrPP3ezDlqNPg759jGzV4MJFZJBccRsZb+tgJqu3LwXKY06d07jPPOlyn7nJqLJ1iYX5Q6iYapSFxZ9WGPbE6A/QGy2/LYEe5sjSTy4We9xO3Dypk3oSkOiDIOdbl6/8PwT7BVj3aDmsd15kZLtkP/Buzv4iWrfoabK1XzAVTpPwJnXrBUZg0mw9dc7KPi559lpR/dGaACnDfpu461YVQPzZgK9aTrJDXG/mWR1TX8Dfra0i0D1cYGICqtJ90s+F8JPXLQcC1YH4drgZSlTA7A3k+G4bOHgB9ePZ7DmU7aSviV3u6DgYkxYsvQwgHMP3ltiWhIw83fXV0ApLllr2R8u6zqKSdiIBFPIQKHHMJQ/vQqw0v22s9FAnQtaqwE5Z1Mm6oAWd2Kevv3Oaz3GAkSE=

after_success:
- npm run ci:automerge
- npm run ci:build:auth
