version: "2"
services:
  web-app:
    build: web-app
    ports:
    - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    env_file:
    - ./devops/config/normal-dev.env

  auth-svc:
    build: auth-service
    ports:
    - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
    - ./devops/config/normal-dev.env
    depends_on:
    - mongo

  posts-svc:
    build: posts-service
    ports:
    - "${POSTS_PORT}:${POSTS_PORT}"
    env_file:
    - ./devops/config/normal-dev.env
    environment:
      - AUTH_HOST=auth-svc
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
