version: "2"
services:
  web-app:
    build: web-app
    ports:
    - "${WEB_APP_PORT}:${WEB_APP_PORT}"

  auth-svc:
    image: antkozdocker/pdp-auth-svc:latest
    ports:
    - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
    - ./devops/config/normal-dev.env
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
