version: "2"
services:
  auth-svc:
    build: auth-service
    ports:
    - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
    - ./devops/config/normal-dev.env
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
