version: "2"
services:
  auth-svc:
    build: .
    ports:
    - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
    - ./config/normal-dev.env
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "${MONGO_PORT}:${MONGO_PORT}"
